### ISSUE TITLE
creating acl's in WARP results in unexpected file name 

### ISSUE THREAD

**Issue by cptvitamin** [linkeddata/warp#13]
I'm using ldnode 0.2.16.  When I attempt to alter permissions on file 'main', it creates an acl file named `mainmain.acl`.  Expected `main.acl`  

I believe this is a fairly serious bug since when ldnode checks for acls on a file, it looks for filename.acl and not filenamefilename.acl

**Comment by nicola** [comment]
hey @cptvitamin are you setting the ACL via the permission editor, or you are just creating a new file?

**Comment by cptvitamin** [comment]
@nicola I am using the permission editor.

**Comment by nicola** [comment]
@deiu any idea?

**Comment by deiu** [comment]
Fixed in c51f16911a30616d83d422794b6e789088345996
