### ISSUE TITLE
Proxy points to rww.io

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/warp#22]
The proxy in warp has as default rww.io

https://github.com/linkeddata/warp/blob/e9c16b98b4116eb577ac4b69b54473f4585f1407/src/app/app.js#L2

If rww.io going to be decommissioned this will cause client errors.

Better would be to default to another server e.g. databox.me or databox2.com

**Comment by chrysn** [comment]
This was fixed in 66d9250.
