### ISSUE TITLE
Unauthorized requests

### ISSUE THREAD

**Issue by Otto-AA** [linkeddata/warp#27]
This app seems really promising for managing files in the pod, yet it appears to me, that no requests are authorized.

For instance, I've tried to delete https://otman.solid.community/public/test/test.txt via the dropdown menu, but in the whole process I never was prompted to login. Therefore the DELETE request was rejected with `401 Unauthorized`. The same problem occurs while uploading a file.

Did I miss something, or is this just not implemented yet?

**Comment by RubenVerborgh** [comment]
Warp is only compatible with WebID+TLS, not with WebID+OIDC (which is what solid.community is using).
